export default {
  login: "saltysquid",
  id: 15126442,
  node_id: "MDQ6VXNlcjE1MTI2NDQy",
  avatar_url: "https://avatars.githubusercontent.com/u/15126442?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/saltysquid",
  html_url: "https://github.com/saltysquid",
  followers_url: "https://api.github.com/users/saltysquid/followers",
  following_url:
    "https://api.github.com/users/saltysquid/following{/other_user}",
  gists_url: "https://api.github.com/users/saltysquid/gists{/gist_id}",
  starred_url: "https://api.github.com/users/saltysquid/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/saltysquid/subscriptions",
  organizations_url: "https://api.github.com/users/saltysquid/orgs",
  repos_url: "https://api.github.com/users/saltysquid/repos",
  events_url: "https://api.github.com/users/saltysquid/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/saltysquid/received_events",
  type: "User",
  site_admin: false,
  name: "Brian",
  company: "squiddy ink",
  blog: "www.squiddy.ink",
  location: "Tallahassee, FL",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 9,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2015-10-14T14:35:27Z",
  updated_at: "2021-02-23T03:20:45Z",
};
